### ISSUE TITLE
`rack data import` fails on `MIL-STD-881D.owl`

### ISSUE THREAD

**Issue by Ptival** [ge-high-assurance/RACK#435]
Command: `rack data import --clear ../RACK-Ontology/OwlModels/MIL-STD-881D.owl`

Error:
```
Traceback (most recent call last):
  File "/Users/val/galois/arcos/RACK/cli/.venv/bin/rack", line 69, in <module>
    func(args)
  File "/Users/val/galois/arcos/RACK/cli/.venv/lib/python3.9/site-packages/rack/__init__.py", line 451, in dispatch_data_import
    ingest_data_driver(Path(args.config), args.base_url, args.data_graph, args.triple_store, args.clear)
  File "/Users/val/galois/arcos/RACK/cli/.venv/lib/python3.9/site-packages/rack/__init__.py", line 295, in ingest_data_driver
    validate(config, INGEST_CSV_CONFIG_SCHEMA)
  File "/Users/val/galois/arcos/RACK/cli/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: '<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:j.0="http://arcos.rack/PROV-S#" xmlns:m881D="http://arcos.rack/MIL-STD-881D/MIL-STD-881D#" xmlns:sys="http://arcos.rack/SYSTEM#" xmlns:builtinfunctions="http://sadl.org/builtinfunctions#" xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:Pr="http://arcos.rack/PROCESS#" xmlns:sadlimplicitmodel="http://sadl.org/sadlimplicitmodel#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:D="http://arcos.rack/DOCUMENT#" xmlns:sadlbasemodel="http://sadl.org/sadlbasemodel#" xmlns:xsd="http://www.w3.org/2001/XMLSchema#" xml:base="http://arcos.rack/MIL-STD-881D/MIL-STD-881D"> <owl:Ontology rdf:about=""> <owl:imports rdf:resource="/DOCUMENT"/> <owl:imports rdf:resource="/PROCESS"/> <owl:imports rdf:resource="/SYSTEM"/> <owl:imports rdf:resource="http://sadl.org/builtinfunctions"/> <owl:imports rdf:resource="http://sadl.org/sadlimplicitmodel"/> <owl:imports rdf:resource="http://sadl.org/sadlbasemodel"/> <rdfs:comment xml:lang="en">This ontology was created from a SADL file \'MIL-STD-881D.sadl\' and should not be directly edited.</rdfs:comment> </owl:Ontology> <owl:FunctionalProperty rdf:ID="wbs"> <rdfs:comment xml:lang="en">This is the WBS (Work Breakdown Structure) string from MIL-STD-881D</rdfs:comment> <rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#string"/> <rdfs:domain rdf:resource="/SYSTEM#SYSTEM"/> <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#DatatypeProperty"/> </owl:FunctionalProperty> <D:SPECIFICATION rdf:ID="MIL-STD-881D"> <j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxE"/> </j.0:content> <j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxH"/> </j.0:content> <j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxB"/> </j.0:content> <j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxC"/> </j.0:content> <j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxK"/> </j.0:content> <j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxF"/> </j.0:content> <j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxL"/> </j.0:content> <j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxG"/> </j.0:content> <j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxA"/> </j.0:content> <D:dateOfIssue rdf:datatype="http://www.w3.org/2001/XMLSchema#date" >2018-04-09</D:dateOfIssue> <D:status rdf:resource="/DOCUMENT#Released"/> <j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxI"/> </j.0:content> <j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxD"/> </j.0:content> <j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxJ"/> </j.0:content> </D:SPECIFICATION> </rdf:RDF>' is not of type 'object'

Failed validating 'type' in schema:
    {'additionalProperties': False,
     'properties': {'data-graph': {'type': 'string'},
                    'extra-data-graphs': {'contains': {'type': 'string'},
                                          'type': 'array'},
                    'ingestion-steps': {'items': {'oneOf': [{'additionalProperties': False,
                                                             'properties': {'csv': {'type': 'string'},
                                                                            'nodegroup': {'type': 'string'}},
                                                             'required': ['nodegroup',
                                                                          'csv'],
                                                             'type': 'object'},
                                                            {'addtionalProperties': False,
                                                             'properties': {'owl': {'type': 'string'}},
                                                             'required': ['owl'],
                                                             'type': 'object'}]},
                                        'type': 'array'}},
     'required': ['ingestion-steps'],
     'type': 'object'}

On instance:
    ('<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" '
     'xmlns:j.0="http://arcos.rack/PROV-S#" '
     'xmlns:m881D="http://arcos.rack/MIL-STD-881D/MIL-STD-881D#" '
     'xmlns:sys="http://arcos.rack/SYSTEM#" '
     'xmlns:builtinfunctions="http://sadl.org/builtinfunctions#" '
     'xmlns:owl="http://www.w3.org/2002/07/owl#" '
     'xmlns:Pr="http://arcos.rack/PROCESS#" '
     'xmlns:sadlimplicitmodel="http://sadl.org/sadlimplicitmodel#" '
     'xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" '
     'xmlns:D="http://arcos.rack/DOCUMENT#" '
     'xmlns:sadlbasemodel="http://sadl.org/sadlbasemodel#" '
     'xmlns:xsd="http://www.w3.org/2001/XMLSchema#" '
     'xml:base="http://arcos.rack/MIL-STD-881D/MIL-STD-881D"> '
     '<owl:Ontology rdf:about=""> <owl:imports rdf:resource="/DOCUMENT"/> '
     '<owl:imports rdf:resource="/PROCESS"/> <owl:imports '
     'rdf:resource="/SYSTEM"/> <owl:imports '
     'rdf:resource="http://sadl.org/builtinfunctions"/> <owl:imports '
     'rdf:resource="http://sadl.org/sadlimplicitmodel"/> <owl:imports '
     'rdf:resource="http://sadl.org/sadlbasemodel"/> <rdfs:comment '
     'xml:lang="en">This ontology was created from a SADL file '
     "'MIL-STD-881D.sadl' and should not be directly "
     'edited.</rdfs:comment> </owl:Ontology> <owl:FunctionalProperty '
     'rdf:ID="wbs"> <rdfs:comment xml:lang="en">This is the WBS (Work '
     'Breakdown Structure) string from MIL-STD-881D</rdfs:comment> '
     '<rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#string"/> '
     '<rdfs:domain rdf:resource="/SYSTEM#SYSTEM"/> <rdf:type '
     'rdf:resource="http://www.w3.org/2002/07/owl#DatatypeProperty"/> '
     '</owl:FunctionalProperty> <D:SPECIFICATION rdf:ID="MIL-STD-881D"> '
     '<j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxE"/> '
     '</j.0:content> <j.0:content> <D:SECTION '
     'rdf:ID="MIL-STD-881D-AppxH"/> </j.0:content> <j.0:content> '
     '<D:SECTION rdf:ID="MIL-STD-881D-AppxB"/> </j.0:content> '
     '<j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxC"/> '
     '</j.0:content> <j.0:content> <D:SECTION '
     'rdf:ID="MIL-STD-881D-AppxK"/> </j.0:content> <j.0:content> '
     '<D:SECTION rdf:ID="MIL-STD-881D-AppxF"/> </j.0:content> '
     '<j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxL"/> '
     '</j.0:content> <j.0:content> <D:SECTION '
     'rdf:ID="MIL-STD-881D-AppxG"/> </j.0:content> <j.0:content> '
     '<D:SECTION rdf:ID="MIL-STD-881D-AppxA"/> </j.0:content> '
     '<D:dateOfIssue rdf:datatype="http://www.w3.org/2001/XMLSchema#date" '
     '>2018-04-09</D:dateOfIssue> <D:status '
     'rdf:resource="/DOCUMENT#Released"/> <j.0:content> <D:SECTION '
     'rdf:ID="MIL-STD-881D-AppxI"/> </j.0:content> <j.0:content> '
     '<D:SECTION rdf:ID="MIL-STD-881D-AppxD"/> </j.0:content> '
     '<j.0:content> <D:SECTION rdf:ID="MIL-STD-881D-AppxJ"/> '
     '</j.0:content> </D:SPECIFICATION> </rdf:RDF>')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/val/galois/arcos/RACK/cli/.venv/bin/rack", line 83, in <module>
    instance_keys = set(exc.instance.keys())
AttributeError: 'str' object has no attribute 'keys'
```

**Comment by Ptival** [comment]
Actually, it fails on all three of ARP-4754A, DO-330, MIL-STD-881D.

It does succeed on DO-178C.

**Comment by Ptival** [comment]
My bad, accidentally completed to `owl` rather than `yaml` and did not notice!
