### ISSUE TITLE
Fix THREAT ingestion in latest package

### ISSUE THREAD

**Issue by cuddihyge** [ge-high-assurance/RACK#685]

**Comment by cuddihyge** [comment]
Kit has found this error in the latest 'dev' docker container:


```
(venv)
200005944@G1FDWN13E MINGW64 /c/Data/GitHub/RACK/cli (master)
$ ./setup-arcos.sh
Ingesting ..\Boeing-Ontology\OwlModels\Boeing.owl...OK
Storing nodegroups...                                       OK
Ingesting ..\GrammaTech-Ontology\OwlModels\GrammaTech.owl...OK
Storing nodegroups...                                       OK
Ingesting ..\LM-Ontology\OwlModels\LM.owl...       OK
Storing nodegroups...                                       OK
Ingesting ..\SRI-Ontology\OwlModels\SRI.owl...     OK
Ingesting ..\SRI-Ontology\OwlModels\SRI-SS.owl...  OK
Storing nodegroups...                                       OK
Ingesting ..\STR-Ontology\OwlModels\STR.owl...     OK
Storing nodegroups...                                       OK
Ingesting ..\RACK-Ontology\OwlModels\MITRE-CWE.owl...OK
Storing nodegroups...                                       OK
Clearing graph
Success Update succeeded
Loading CWE ingestion...                           OK Records: 419
Loading CWE effectivenesses...                     OK Records: 6
Loading CWE methods...                             OK Records: 17
Loading CWE effectiveness association...           OK Records: 228
Loading ingest_THREAT...                           OK Records: 546
Loading ingest_THREAT...                           FAIL
Traceback (most recent call last):
  File "C:/Data/GitHub/RACK/cli/venv/Scripts/rack", line 4, in <module>
    __import__('pkg_resources').run_script('rack==0.0.0', 'rack')
  File "C:\Data\GitHub\RACK\cli\venv\lib\site-packages\pkg_resources\__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Data\GitHub\RACK\cli\venv\lib\site-packages\pkg_resources\__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "C:\Data\GitHub\RACK\cli\venv\lib\site-packages\rack-0.0.0-py3.8.egg\EGG-INFO\scripts\rack", line 69, in <module>
  File "C:\Data\GitHub\RACK\cli\venv\lib\site-packages\rack-0.0.0-py3.8.egg\rack\__init__.py", line 451, in dispatch_data_import
  File "C:\Data\GitHub\RACK\cli\venv\lib\site-packages\rack-0.0.0-py3.8.egg\rack\__init__.py", line 332, in ingest_data_driver
  File "C:\Data\GitHub\RACK\cli\venv\lib\site-packages\rack-0.0.0-py3.8.egg\rack\__init__.py", line 282, in ingest_csv
  File "C:\Data\GitHub\RACK\cli\venv\lib\site-packages\rack-0.0.0-py3.8.egg\rack\__init__.py", line 170, in wrapper
  File "C:\Data\GitHub\RACK\cli\venv\lib\site-packages\rack-0.0.0-py3.8.egg\rack\__init__.py", line 167, in wrapper
  File "C:\Data\GitHub\RACK\cli\venv\lib\site-packages\rack-0.0.0-py3.8.egg\rack\__init__.py", line 280, in go
  File "C:\Data\GitHub\RACK\cli\venv\lib\site-packages\semtk3\__init__.py", line 279, in ingest_by_id
    table = nge_client.exec_async_ingest_from_csv(nodegroup_id, csv_str, override_conn_json_str)
  File "C:\Data\GitHub\RACK\cli\venv\lib\site-packages\semtk3\nodegroupexecclient.py", line 144, in exec_async_ingest_from_csv
    res = self.post_to_record_process("ingestFromCsvStringsById", payload)
  File "C:\Data\GitHub\RACK\cli\venv\lib\site-packages\semtk3\semtkclient.py", line 168, in post_to_record_process
    raise Exception("Encountered failures: \n" + t.get_csv_string())
Exception: Encountered failures:
identifier,wasimpactedby_identifier,Failure Cause,Failure Record Number
CAPEC-1,CWE-285,URI lookup on [?ENTITY_0] failed on: CWE-285,2
CAPEC-1,CWE-693,URI lookup on [?ENTITY_0] failed on: CWE-693,4
CAPEC-1,CWE-732,URI lookup on [?ENTITY_0] failed on: CWE-732,5
CAPEC-1,CWE-1193,URI lookup on [?ENTITY_0] failed on: CWE-1193,6
```

**Comment by cuddihyge** [comment]
1. MITRE_CWE.csv doesn’t contain “CWE-285” which is ingested by the first step in import.yaml 
    {nodegroup: "CWE ingestion", csv: "MITRE_CWE.csv" }
1. CAPEC_CWE.csv  does reference “CWE-285”. it is looked up (and fails) during  the last step  with 
        {nodegroup: "ingest_THREAT", csv: "CAPEC_CWE.csv" }

Why is 10.0 set to "Create-if-missing" and the dev version is set to "Error-if-missing" ?    [Paul]
Why is 285 missing from the data [Eric]

**Comment by cuddihyge** [comment]
I've found logic in the ingestion nodegroup generator that I don't particularly like.
If a linked node has no subclasses, then it is CREATE_IF_MISSING.    Otherwise it is ERROR_IF_MISSING.

I think only the main node should ever be CREATE_IF_MISSING.

**Question:   Did THREAT->wasImpactedBy change to a higher class (ENTITY?) for the dev release?    If so, that would have triggered this logic.**
